import type { ApiArtifact, ArtifactEndpoint, MapperStep } from "../artifact/types.js";
import { sha256 } from "./hash.js";

export function generateApiCode(artifact: ApiArtifact): string {
  const body = [
    "/* eslint-disable */",
    "/* This file is generated by mockoon-gen. Do not edit by hand unless you accept it back into the artifact workflow. */",
    "declare function request<T>(path: string, options?: { method?: string; body?: unknown }): Promise<T>;",
    "",
    ...artifact.endpoints.flatMap((endpoint) => generateEndpoint(endpoint, artifact.outputs.apiCode.transformResponse))
  ].join("\n");

  return `/* mockoon-gen-sha256: ${sha256(body)} */\n${body}\n`;
}

function generateEndpoint(endpoint: ArtifactEndpoint, transformResponse: boolean): string[] {
  const dto = endpoint.dto.response;
  const vo = endpoint.vo.name;
  const mapper = endpoint.mapper.name;
  const responseType = transformResponse ? vo : dto;

  return [
    `export interface ${dto} {`,
    ...endpoint.vo.fields.map((field) => `  ${dtoFieldName(field.sources[0]?.path ?? field.name)}: ${field.type};`),
    "}",
    "",
    `export interface ${vo} {`,
    ...endpoint.vo.fields.map((field) => `  ${field.name}: ${field.type};`),
    "}",
    "",
    `export function ${mapper}(dto: ${dto}): ${vo} {`,
    `  const vo = {} as ${vo};`,
    ...endpoint.mapper.steps.slice().sort((left, right) => left.order - right.order).map((step) => generateMapperStep(step)),
    "  return vo;",
    "}",
    "",
    `export async function ${endpoint.operationId}(): Promise<${responseType}> {`,
    transformResponse
      ? `  const dto = await request<${dto}>("${endpoint.path}", { method: "${endpoint.method}" });`
      : `  return request<${dto}>("${endpoint.path}", { method: "${endpoint.method}" });`,
    transformResponse ? `  return ${mapper}(dto);` : "",
    "}",
    ""
  ].filter((line) => line !== "");
}

function generateMapperStep(step: MapperStep): string {
  if (step.operation === "rename" || step.operation === "assign") {
    return `  ${step.output} = ${step.inputs[0]?.replace(/^response\.body\./, "dto.") ?? "undefined"};`;
  }

  return `  // needsReview: Unsupported mapper operation ${step.operation}`;
}

function dtoFieldName(path: string): string {
  const segments = path.split(".");
  return segments[segments.length - 1] ?? path;
}
